"""v1.9

Revision ID: 0280d6719b7d
Revises: 690a4b8c1a65
Create Date: 2021-10-11 14:09:54.438212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0280d6719b7d'
down_revision = '690a4b8c1a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namstasks', sa.Column('runtime_todayed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_namstasks_runtime_todayed'), 'namstasks', ['runtime_todayed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namstasks_runtime_todayed'), table_name='namstasks')
    op.drop_column('namstasks', 'runtime_todayed')
    # ### end Alembic commands ###
