"""v.5

Revision ID: 22a53cd27e0c
Revises: b0b7e1ed6c6c
Create Date: 2021-10-09 14:11:00.493355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a53cd27e0c'
down_revision = 'b0b7e1ed6c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namstasks', sa.Column('alive', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_namstasks_alive'), 'namstasks', ['alive'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namstasks_alive'), table_name='namstasks')
    op.drop_column('namstasks', 'alive')
    # ### end Alembic commands ###
