"""v2.7

Revision ID: 2b1637f1c0f6
Revises: 33fbaa2b042d
Create Date: 2021-10-16 16:18:02.438170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1637f1c0f6'
down_revision = '33fbaa2b042d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty', sa.Text(), nullable=True),
    sa.Column('remember_info', sa.Text(), nullable=True),
    sa.Column('rememberinfo_show', sa.Text(), nullable=True),
    sa.Column('deadline_time', sa.DateTime(), nullable=True),
    sa.Column('todayed', sa.Boolean(), nullable=True),
    sa.Column('overdrafted', sa.Boolean(), nullable=True),
    sa.Column('attachmentfile_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_duty'), 'deadlines', ['duty'], unique=True)
    op.create_index(op.f('ix_deadlines_overdrafted'), 'deadlines', ['overdrafted'], unique=False)
    op.create_index(op.f('ix_deadlines_todayed'), 'deadlines', ['todayed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deadlines_todayed'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_overdrafted'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_duty'), table_name='deadlines')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
