"""'addednewmode'

Revision ID: 2ca3b7a7a343
Revises: c4c0c1ed1554
Create Date: 2021-10-07 09:23:14.265648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca3b7a7a343'
down_revision = 'c4c0c1ed1554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasktypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasktypes_name'), 'tasktypes', ['name'], unique=False)
    op.create_table('namstasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskname', sa.Text(), nullable=True),
    sa.Column('runtime', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('thisinfo_creationtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['tasktypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namstasks_finished'), 'namstasks', ['finished'], unique=False)
    op.create_index(op.f('ix_namstasks_runtime'), 'namstasks', ['runtime'], unique=False)
    op.create_index(op.f('ix_namstasks_taskname'), 'namstasks', ['taskname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namstasks_taskname'), table_name='namstasks')
    op.drop_index(op.f('ix_namstasks_runtime'), table_name='namstasks')
    op.drop_index(op.f('ix_namstasks_finished'), table_name='namstasks')
    op.drop_table('namstasks')
    op.drop_index(op.f('ix_tasktypes_name'), table_name='tasktypes')
    op.drop_table('tasktypes')
    # ### end Alembic commands ###
