"""v2.6

Revision ID: 33fbaa2b042d
Revises: d39010a2bc5a
Create Date: 2021-10-15 21:22:26.323707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33fbaa2b042d'
down_revision = 'd39010a2bc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namsinsulins', sa.Column('alerted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_namsinsulins_alerted'), 'namsinsulins', ['alerted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namsinsulins_alerted'), table_name='namsinsulins')
    op.drop_column('namsinsulins', 'alerted')
    # ### end Alembic commands ###
