"""v2.8

Revision ID: 342e0c9784a7
Revises: 2b1637f1c0f6
Create Date: 2021-10-17 11:48:24.265627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342e0c9784a7'
down_revision = '2b1637f1c0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadlines', 'image_url')
    # ### end Alembic commands ###
