"""v1.3

Revision ID: 3a1add54f924
Revises: c2c8b6d9a6e4
Create Date: 2021-10-08 19:53:42.776826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1add54f924'
down_revision = 'c2c8b6d9a6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namstasks', sa.Column('matching_searchrequest', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_namstasks_matching_searchrequest'), 'namstasks', ['matching_searchrequest'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namstasks_matching_searchrequest'), table_name='namstasks')
    op.drop_column('namstasks', 'matching_searchrequest')
    # ### end Alembic commands ###
