"""v1.7

Revision ID: 690a4b8c1a65
Revises: d4801bac71dc
Create Date: 2021-10-11 10:11:30.816210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690a4b8c1a65'
down_revision = 'd4801bac71dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insulins_full_name', table_name='insulins')
    op.create_index(op.f('ix_insulins_full_name'), 'insulins', ['full_name'], unique=True)
    op.add_column('namsinsulins', sa.Column('info', sa.Text(), nullable=True))
    op.add_column('namsinsulins', sa.Column('currently_inuse', sa.Boolean(), nullable=True))
    op.add_column('namsinsulins', sa.Column('startusing_since', sa.DateTime(), nullable=True))
    op.add_column('namsinsulins', sa.Column('stopusing_since', sa.DateTime(), nullable=True))
    op.drop_index('ix_namsinsulins_insulin_name', table_name='namsinsulins')
    op.create_index(op.f('ix_namsinsulins_insulin_name'), 'namsinsulins', ['insulin_name'], unique=True)
    op.create_index(op.f('ix_namsinsulins_currently_inuse'), 'namsinsulins', ['currently_inuse'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namsinsulins_currently_inuse'), table_name='namsinsulins')
    op.drop_index(op.f('ix_namsinsulins_insulin_name'), table_name='namsinsulins')
    op.create_index('ix_namsinsulins_insulin_name', 'namsinsulins', ['insulin_name'], unique=False)
    op.drop_column('namsinsulins', 'stopusing_since')
    op.drop_column('namsinsulins', 'startusing_since')
    op.drop_column('namsinsulins', 'currently_inuse')
    op.drop_column('namsinsulins', 'info')
    op.drop_index(op.f('ix_insulins_full_name'), table_name='insulins')
    op.create_index('ix_insulins_full_name', 'insulins', ['full_name'], unique=False)
    # ### end Alembic commands ###
