"""v1.6

Revision ID: 8c7798ba681e
Revises: 22a53cd27e0c
Create Date: 2021-10-09 15:44:24.956261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7798ba681e'
down_revision = '22a53cd27e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namstasks', sa.Column('trashed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_namstasks_trashed'), 'namstasks', ['trashed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namstasks_trashed'), table_name='namstasks')
    op.drop_column('namstasks', 'trashed')
    # ### end Alembic commands ###
