"""'updatePostqueryattr'

Revision ID: a35433688f34
Revises: bc32fbef85d9
Create Date: 2021-09-27 11:44:51.309723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35433688f34'
down_revision = 'bc32fbef85d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('toquery_authornamestartswithu', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_posts_toquery_authornamestartswithu'), 'posts', ['toquery_authornamestartswithu'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_toquery_authornamestartswithu'), table_name='posts')
    op.drop_column('posts', 'toquery_authornamestartswithu')
    # ### end Alembic commands ###
