"""v2.0

Revision ID: aee183fff26c
Revises: 0280d6719b7d
Create Date: 2021-10-12 15:49:49.298475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee183fff26c'
down_revision = '0280d6719b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insulins', sa.Column('storing_unit', sa.Text(), nullable=True))
    op.add_column('insulins', sa.Column('amount_perstoringunit', sa.Text(), nullable=True))
    op.add_column('namsinsulins', sa.Column('lasttime_pumpchange_timestamp', sa.DateTime(), nullable=True))
    op.add_column('namsinsulins', sa.Column('lasttime_pumpchange_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namsinsulins', 'lasttime_pumpchange_info')
    op.drop_column('namsinsulins', 'lasttime_pumpchange_timestamp')
    op.drop_column('insulins', 'amount_perstoringunit')
    op.drop_column('insulins', 'storing_unit')
    # ### end Alembic commands ###
