"""'updatemodelcomment'

Revision ID: c4c0c1ed1554
Revises: a35433688f34
Create Date: 2021-09-27 15:33:32.486350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c0c1ed1554'
down_revision = 'a35433688f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentsss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentsss_timestamp'), 'commentsss', ['timestamp'], unique=False)
    op.drop_index('ix_posts_toquery_authornamestartswithu', table_name='posts')
    op.drop_column('posts', 'toquery_authornamestartswithu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('toquery_authornamestartswithu', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_posts_toquery_authornamestartswithu', 'posts', ['toquery_authornamestartswithu'], unique=False)
    op.drop_index(op.f('ix_commentsss_timestamp'), table_name='commentsss')
    op.drop_table('commentsss')
    # ### end Alembic commands ###
