"""v2.4

Revision ID: caf7feb3c0e6
Revises: ea23700443ce
Create Date: 2021-10-15 14:34:55.314153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf7feb3c0e6'
down_revision = 'ea23700443ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namsinsulins', sa.Column('numberofdays_enoughinsulin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namsinsulins', 'numberofdays_enoughinsulin')
    # ### end Alembic commands ###
