"""v2.5

Revision ID: d39010a2bc5a
Revises: caf7feb3c0e6
Create Date: 2021-10-15 15:16:28.022143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39010a2bc5a'
down_revision = 'caf7feb3c0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namsinsulins', sa.Column('lasttimepoint_updatebalance', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namsinsulins', 'lasttimepoint_updatebalance')
    # ### end Alembic commands ###
