"""v1.7

Revision ID: d4801bac71dc
Revises: 8c7798ba681e
Create Date: 2021-10-10 22:53:52.913049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4801bac71dc'
down_revision = '8c7798ba681e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insulins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insulins_full_name'), 'insulins', ['full_name'], unique=False)
    op.create_table('namsinsulins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('insulin_name', sa.Text(), nullable=True),
    sa.Column('last_purchasetime', sa.DateTime(), nullable=True),
    sa.Column('lastpurchasetime_info', sa.Text(), nullable=True),
    sa.Column('avgamount_perday', sa.Integer(), nullable=True),
    sa.Column('avgamount_pertime', sa.Integer(), nullable=True),
    sa.Column('current_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['insulins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namsinsulins_insulin_name'), 'namsinsulins', ['insulin_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_namsinsulins_insulin_name'), table_name='namsinsulins')
    op.drop_table('namsinsulins')
    op.drop_index(op.f('ix_insulins_full_name'), table_name='insulins')
    op.drop_table('insulins')
    # ### end Alembic commands ###
