"""v3

Revision ID: dd55d4abe1a9
Revises: 342e0c9784a7
Create Date: 2021-10-20 07:25:53.263425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd55d4abe1a9'
down_revision = '342e0c9784a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namstasks', sa.Column('est_endtime', sa.DateTime(), nullable=True))
    op.add_column('namstasks', sa.Column('overlapping', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namstasks', 'overlapping')
    op.drop_column('namstasks', 'est_endtime')
    # ### end Alembic commands ###
