"""v2.1

Revision ID: f92668e7282f
Revises: aee183fff26c
Create Date: 2021-10-13 10:17:55.104775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92668e7282f'
down_revision = 'aee183fff26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insulins', sa.Column('full_descriptionshow', sa.Text(), nullable=True))
    op.add_column('namsinsulins', sa.Column('info_show', sa.Text(), nullable=True))
    op.add_column('namstasks', sa.Column('info_show', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namstasks', 'info_show')
    op.drop_column('namsinsulins', 'info_show')
    op.drop_column('insulins', 'full_descriptionshow')
    # ### end Alembic commands ###
