"""'patching'

Revision ID: 631dd3531394
Revises: 
Create Date: 2021-09-15 11:41:10.694312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631dd3531394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trytable')
    op.add_column('roles', sa.Column('rolename', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'roles', ['rolename'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'rolename')
    op.create_table('trytable',
    sa.Column('SQLite format 3', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
